server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lhl.springcloud.entity          # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: microservicecloud-dept   # 注册进Eureka之后 Application显示的名字
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://123.206.180.67:3306/cloudDB02?useSSL=false              # 数据库名称
    username: root
    password: 1132214759a
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

# Eureka client 注册进 Eureka server      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
# 单机     defaultZone: http://localhost:7001/eureka
# 同时注册进三个Eureka服务注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true  # 访问路径可以显示IP地址
 
# Eureka 注册中心点击微服务超链接后需要显示的 Info 信息
info:
  app.name: lhl-microservicecloud
  company.name: nildeveloper.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$