server:
  port: 80

# 控制台彩色字体
spring:
  output:
    ansi:
      enabled: always
      
      
# eureka 注册中心配置
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

# 客户端开启hystrix 服务降级
feign:
  hystrix:
    enabled: true
  